spring:
  #데이터 베이스 연결을 위한 설정
  #데이터베이스 다중화
  datasource:
    #oracle: #메인 데이터베이스 (Oracle)
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521/XEPDB1
      username: SPRING #설정 필요
      password: SPRING #설정 필요
#    postgres:  #보조 데이터베이스 (PostgreSQL)
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/postgres_db
#      username: postgres_user #설정 필요
#      password: postgres_password #설정 필요

#Spring-Data-JPA설정
  jpa:
    hibernate:
      #개발때는 update 하고 배포시에는 none 하자
      ddl-auto: update
      naming:
        #JPA 컬럼명 전략
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #클래스명,필드명 그대로 사용
    properties:
      hibernate:
        format_sql: true #DDL문 가독성 있게 표시
    show-sql: true #JPA 쿼리 로그 확인용.(이 설정을 해야 sql문 볼 수 있음)		